DL-Lab Assignment-1

Name: Pushkar Mundlik
Reg. No: 20MAI0063

Git Hub Link: https://github.com/pknigth/DL-Lab-Assignmnet-1/upload

Problem-1:

In [18]:
import numpy as np

class P:
  #define constructor with parameters learning rate and no of iteration (epoch)
    def __init__(self, learn_rate=0.1, no_of_iteration=100):
    
      self.lr = learn_rate
      self.epochs = no_of_iteration
      self.weights = None
      self.bias = None
    
    def fit(self, X, y):
      self.weights = np.zeros(X.shape[1])
      self.bias = 0

      print("Training Input: \n", X)

      for epoch in range(self.epochs):
          for i in range(X.shape[0]):

              y_pred = self.activation_func(np.dot(self.weights, X[i]) + self.bias)
              y_pred1[i] = y_pred
              self.weights = self.weights + self.lr * (y[i] - y_pred)*X[i]
              self.bias = self.bias + self.lr * (y[i] - y_pred)
      
      print("\nTraining:")
      print("Weights: ", self.weights)
      print("Bias: ", self.bias)

      print("\nActuall Output:", y)
      print("Predicted Output:", y_pred1)

    def activation_func(self, activation):
        if activation>=0:
            return 1
        else:
            return 0
    
    def predict(self, X):
      y_pred = []
      for i in range(X.shape[0]):
          y_pred.append(self.activation_func(np.dot(self.weights, X[i]) + self.bias))

      print("\nTesting:")
      print("Testing Input: ", t)
      print("Testing Predicted Output: ", y_pred)

if __name__ == '__main__':
    X = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

    y = np.array([0, 1, 1]) 
    t = np.array([[4, 7, 8]])

    # for training's predicted output
    y_pred1 = np.array([0, 0, 0])

    perceptron = P()
    perceptron.fit(X, y)

    
    perceptron.predict(t)


Training Input: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Training:
Weights:  [ 0.5  0.1 -0.3]
Bias:  -0.4

Actuall Output: [0 1 1]
Predicted Output: [0 1 1]

Testing:
Testing Input:  [[4 7 8]]
Testing Predicted Output:  [0]
